apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tingtt-portfolio
  namespace: argocd
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: .k8s
    repoURL: 'https://github.com/tingtt/tingtt.git'
    targetRevision: main
  project: tingtt-portfolio
  syncPolicy:
    automated: {}
